############ SCCODA Analysis Inputs ############
# python scooda_analysis.py sccoda_analysis_input/config.yml

# path of partly preprocessed HLCA file used in this notebook:
adata_path : "/home/h/hollenberg/MaPra/datasets_seperate/misharin.h5ad"

# path to results directory: (has to exist)
dir_out : "/home/h/hollenberg/MaPra/sccoda/"

##### specify columns 
# Cell type Annotation
cell_type_identifier : "harmonized_anno" 
# samples 
sample_identifier : "batch" 
# condition 
covariate_obs : "condition"
# Name of first condition  
group1 : "untreated"
# Name of secound condition  
group2 : "asbestos"
# reference cell type
reference_cell_type : "automatic"
