############ SCCODA Analysis Inputs ############
# python scooda_analysis.py sccoda_analysis_input/config.yml

# path of partly preprocessed HLCA file used in this notebook:
adata_path : "/home/h/hollenberg/MaPra/datasets_seperate/galapagos_radiation.h5ad"

# add annotation when not in adata -> "already satisfied" if annotation already in adata
add_annotation : "/home/h/hollenberg/MaPra/datasets_seperate/galapagos_radiation_obs_annotation.csv"

# path to results directory: (has to exist)
dir_out : "/home/h/hollenberg/MaPra/sccoda/"

##### specify columns 
# Cell type Annotation
cell_type_identifier : "annotation" 
# samples 
sample_identifier : "SAMP_ID" 
# condition 
covariate_obs : "SAMP_condition"
# Name of first condition  
group1 : "RAD"
# Name of secound condition  
group2 : "SHAM"
# reference cell type
reference_cell_type : "automatic"


